export const DisabledStatus = {
    disabled:{//전표입력 (기본값)
        date: false,
        account: false,
        company: false,
        note: false,
        unit_price: false,
        amount: false,
        product: false,
        quantity: false,
        briefs: false,
    },
    sales:{//매출
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    purchase: {//매입
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    deposit:{//입금
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    withdrawal:{//출금
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    sale_discount:{//매출할인
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    purchase_discount:{//매입할인
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    sales_replacement:{//매출대체
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    cost:{//관리비
        date: false,
        account: false,
        company: true,
        note: true,
        unit_price: true,
        amount: false,
        product: false,
        quantity: true,
        briefs: false,
    },
    return_delivery:{//반품출고
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    returned_received:{//반품입고
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    }, 
}


export const keyOfAccount ={
    sales: '매출',
    purchase: '매입',
    deposit: '입금',
    withdrawal: '출금',
    sale_discount: '매출할인',
    purchase_discount: '매입할인',
    cost: '관리비',
    return_delivery: '반품출고', 
    sales_replacement: '매출대체',
    returned_received: '반품입고'
}