import { ReceiptCategory, RequestReceipt } from "@/model/types/receipt/type";

export const ReceiptDummy:RequestReceipt[] = [
    {
        receiptId: "1",
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice:99000,
        totalPrice:99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '2',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice:99000,
        totalPrice:99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '3',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice:99000,
        totalPrice:99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '4',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '5',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '6',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '7',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '8',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '9',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '10',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '11',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '12',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '13',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '14',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '15',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '16',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '17',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '18',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '19',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '20',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '21',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '22',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '23',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '24',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '25',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '26',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '27',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '28',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '29',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '30',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '31',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
    {
        receiptId: '32',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 pas-1000',
    },
    {
        receiptId: '33',
        timeStamp: new Date('2025-01-23'),
        category: 'SALE' as ReceiptCategory,
        customerName: '경기도농업기술원 통신실',
        memo: '',
        unitPrice: 99000,
        totalPrice: 99000,
        productName: 'test productName',
        quantity: 1,
        description: '1월분 vx51(5000ansi',
    },
]