import { ReceiptCategory } from "@/model/types/receipt/type";


  export const ReceiptCategoryMap = {
    SALES: "매출",
    SALES_DISCOUNT: "매출할인",
    PURCHASE: "매입",
    PURCHASE_DISCOUNT: "매입할인",
    DEPOSIT: "입금",
    WITHDRAWAL: "출금",
    MAINTENANCE_FEE: "관리비",
    OPERATING_PROFIT: "경상손익",
    SALES_ALTERNATIVE: "매출대체",
    RETURN_OUT: "반품출고",
    RETURN_IN: "반품입고"
};
export const receiptCategoryArr =
    Object.entries(ReceiptCategory).map(([key,value])=>{
        return {
        ['categoryKey']: key,
        ['categoryValue'] :value
        }
    })
  
  
export const DisabledStatus = {
    disabled:{//전표입력 (기본값)
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: false,
        unitPrice: false,
        totalPrice: false,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
    },
    SALES:{//매출
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
    },
    PURCHASE: {//매입
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        productName: false,
        quantity: false,
        description: false,
    },
    DEPOSIT:{//입금
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
    },
    WITHDRAWAL:{//출금
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
    },
    SALES_DISCOUNT:{//매출할인
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
    },
    PURCHASE_DISCOUNT:{//매입할인
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
    },
    SALES_ALTERNATIVE:{//매출대체
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
    },
    MAINTENANCE_FEE:{//관리비
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: true,
        customerId:true,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: true,
        description: false,
    },
    RETURN_OUT:{//반품출고
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
    },
    RETURN_IN:{//반품입고
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
    }, 
}
