
export const DisabledStatus = {
    disabled:{//전표입력 (기본값)
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: false,
        unitPrice: false,
        totalPrice: false,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
        officialName:true,
        officialId:true,
    },
    SALES:{//매출
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
        officialName:true,
        officialId:true,
    },
    PURCHASE: {//매입
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        productName: false,
        quantity: false,
        description: false,
        officialName:true,
        officialId:true,
    },
    DEPOSIT:{//입금
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
        officialName:true,
        officialId:true,
    },
    WITHDRAWAL:{//출금
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
        officialName:true,
        officialId:true,
    },
    SALES_DISCOUNT:{//매출할인
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
        officialName:true,
        officialId:true,
    },
    PURCHASE_DISCOUNT:{//매입할인
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
        officialName:true,
        officialId:true,
    },
    SALES_ALTERNATIVE:{//매출대체
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
        officialName:true,
        officialId:true,
    },
    MAINTENANCE_FEE:{//관리비
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: true,
        customerId:true,
        memo: true,
        unitPrice: true,
        totalPrice: false,
        stockId:true,
        productName: true,
        modelName:true,
        quantity: true,
        description: false,
        officialName:false,
        officialId:false,
    },
    RETURN_OUT:{//반품출고
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
        officialName:true,
        officialId:true,
    },
    RETURN_IN:{//반품입고
        receiptId:false,
        timeStamp: false,
        category: false,
        customerName: false,
        customerId:false,
        memo: true,
        unitPrice: false,
        totalPrice: true,
        stockId:false,
        productName: false,
        modelName:false,
        quantity: false,
        description: false,
        officialName:true,
        officialId:true,
    }, 
}
