export const DisabledStatus = {
    input:{//전표입력
        date: false,
        account: false,
        company: false,
        note: false,
        unit_price: false,
        amount: false,
        product: false,
        quantity: false,
        briefs: false,
    },
    sales:{//매출
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    purchase: {//매입
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    deposit:{//입금
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    withdrawal:{//출금
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    sale_discount:{//매출할인
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    purchase_discount:{//매입할인
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: true,
        amount: false,
        product: true,
        quantity: true,
        briefs: false,
    },
    sales_replacement:{//매출대체
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    cost:{//관리비
        date: false,
        account: false,
        company: true,
        note: true,
        unit_price: true,
        amount: false,
        product: false,
        quantity: true,
        briefs: false,
    },
    return_delivery:{//반품출고
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    },
    returned_received:{//반품입고
        date: false,
        account: false,
        company: false,
        note: true,
        unit_price: false,
        amount: true,
        product: false,
        quantity: false,
        briefs: false,
    }, 
}
