import { Receipt } from "./type";

export const ReceiptDummy:Receipt[] = [
    {
        uuid: '1',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '2',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '3',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '4',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '5',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '6',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '7',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '8',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '9',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '10',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '11',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '12',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '13',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '14',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '15',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '16',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '17',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '18',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '19',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '20',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '21',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '22',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '23',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '24',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '25',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '26',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '27',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '28',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '29',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '30',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '31',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
    {
        uuid: '32',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 pas-1000',
    },
    {
        uuid: '33',
        date: new Date('2025-01-23'),
        account: 'sales',
        company: '경기도농업기술원 통신실',
        note: '',
        unit_price: '99000',
        amount: '99000',
        product: 'test product',
        quantity: '1',
        briefs: '1월분 vx51(5000ansi',
    },
]