import { ReduxProvider } from "./providers"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }:{children:React.ReactNode}) {
  return (
    <html lang="ko">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
