import { ReduxProvider } from "./providers"

export const metadata = {
  title: '다온정보',
  description: 'Generated by Next.js',
  icons :{
    icon: "/assets/daon.png",
  }
}

export default async function RootLayout({ children }:{children:React.ReactNode}) {
  return (
    <html lang="ko">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
